function [waypoints,y_ref, yaw_ref, t_vec] = RandomRoadTraj()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 25.1 (R2025a) and Automated Driving Toolbox 25.1 (R2025a).
% Generated on: 10-Mar-2026 11:09:19

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [42.2 16 0;
    32.6 -22.9 0;
    20.7 -23 0;
    22.1 0.6 0;
    9.3 17.3 0;
    5 -12.3 0;
    -1.2 -13.4 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [43.3 11.6 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [43.3 11.6 0;
    42.6 1.1 0;
    43.5 -4.3 0;
    44.6 -6.6 0;
    44.1 -10.2 0;
    41.7 -13 0;
    38.9 -14.4 0;
    36.3 -17.8 0;
    34.4 -19.6 0;
    30.9 -22 0;
    29.7 -25 0;
    24.4 -26 0;
    20.2 -24.9 0;
    18.1 -19.2 0;
    17.5 -11.5 0;
    16.7 -6.2 0;
    19.8 -4 0;
    22.1 -0.6 0;
    23.6 3.2 0;
    23.6 7.6 0;
    23 11.6 0;
    21.9 13.2 0;
    19.9 16.6 0;
    19.9 16.9 0;
    19.4 17.7 0;
    18.5 18.5 0;
    17.4 18.9 0;
    15 19.4 0;
    14.5 19 0;
    13.8 17.4 0;
    13 16.8 0;
    10.2 16.5 0;
    9 16.5 0;
    7.9 16.2 0;
    6.9 13.4 0;
    6.9 8 0;
    7.7 1.6 0;
    9.4 -0.4 0;
    9.7 -3.8 0;
    9.3 -6.2 0;
    8 -8.1 0;
    3.8 -9.1 0;
    3.5 -9.8 0;
    2.8 -11.5 0;
    0.8 -14 0;
    0.2 -16 0;
    -1.3 -16 0];
speed = [5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5;5];
trajectory(egoVehicle, waypoints, speed);

% Extract Y position and Yaw reference vectors
y_ref = waypoints(:, 2);   % Y position column

% Compute yaw from waypoint-to-waypoint directions
dx = diff(waypoints(:,1));
dy = diff(waypoints(:,2));
yaw_vec = atan2(dy, dx);  % in radians, or use atan2d for degrees

% Repeat last value to match 47x1 size
yaw_ref = [yaw_vec; yaw_vec(end)];

% Y reference
y_ref = waypoints(:, 2);
yaw_ref = unwrap(yaw_ref);
% Compute cumulative time vector from waypoint distances and speed
dists = sqrt(diff(waypoints(:,1)).^2 + diff(waypoints(:,2)).^2);
t_vec = [0; cumsum(dists ./ speed(1:end-1))];
