// Simulation environment for the DARPA Tactical Mapping Project
// Author: Julius Allen Marshall
// Date Created: March 10th, 2022
// Last Modified: March 10th, 2022
// Contact: mjulius@vt.edu

// File Decscription ####################################################################################
// This source file implements the A* path planning algorithm to confirm
// feasibility of the goal generated by the goal generation algorithm.
// End File Decscription ################################################################################

// List include files
#include <astar.h>

// Constant integers capturing the map's dimensions
const int grid_x = 100;
const int grid_y = 30;
const int grid_z = 100;

// Define the connectivity of the graph which represents a voxel map
#define DIRECTIONS 24

// Define the movements allowable on this graph, as well as the reverse movements
int dx[DIRECTIONS] = {1, 0, -1, 0, 1,  1, -1, -1, 1, 0, -1,  0, 1,  1, -1, -1,  1,  0, -1,  0,  1,  1, -1, -1};
int dy[DIRECTIONS] = {0, 1, 0, -1, 1, -1,  1, -1, 0, 1,  0, -1, 1, -1,  1, -1,  0,  1,  0, -1,  1, -1,  1, -1};
int dz[DIRECTIONS] = {0, 0, 0,  0, 0,  0,  0,  0, 1, 1,  1,  1, 1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1};
int flip[DIRECTIONS] = {2, 3, 0, 1, 7, 6, 5, 4, 18, 19, 16, 17, 23, 22, 21, 20, 10, 11, 8, 9, 15, 14, 13, 12};
int d_obs[DIRECTIONS] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

// Total number of neighbors per cell
#define NUM_MOVES 24 // NUM_MOVES = DIRECTIONS * d_stride

// BASE used to enable storage of g+h and h in a single number
int BASE = 10000;

// LARGE is used to represent infinity
int LARGE = 99999;

// Prototype structure
struct cell;

// Type definition of a cell
typedef struct cell cell;

// Cell structure definition
struct cell
{

	// Cell coordinates (in the grid)
  int x, y, z;

  // Pointer to a cell, this encodes the movements from the current cell
  cell *move[NUM_MOVES];

  // Pointer to the predecessor of the current cell in the search algorithm
  cell *searchtree;

  // Boolean capturing the occupancy status of the cell
  bool obstacle;

  // float captuing the cost-to-come
  float g;

  // float captuing the rhs value (it's like a pseudo cost-to-come that should be equal to the cost-to-come for the cell to be "locally consistent")
  float rhs;

  // float captuing the heuristic value
  float h;

  // float captuing the cell's key (utilizes BASE to store two values in one number)
  float key;

  // integer used in maintaining the heap (open queue)
  int heapindex;

  // integer capturing how many times the cell has been updated relative to the voxel map
  int iteration;

}; // struct cell

// triple pointer to the maze, initially set to NULL
cell ***maze = NULL;

// pointers to cells that capture the start, goal, and previous goal
cell *mazestart, *mazegoal;

// integer captuing the number of times the voxel map has been updated (without replanning from scratch)
int mazeiteration = 0;

// Define the heapsize (used to preallocate memory for the heap)
// This should be an overestimate of the number of expected locally inconsistent cells in the voxel map (could be the total number of voxels)
#define HEAPSIZE 100000

// Pointer to HEAPSIZE cells
cell *heap[HEAPSIZE];

// Integer captuing the actual size of the heap (how many cells from the maze are in the heap)
int heapsize = 0;


// Member function of Planner class
// initialize: sets up the maze
// INPUTS: none
// OUTPUTS: none
void Planner::initialize()
{

	maze = (cell ***)calloc(MAZEHEIGHT, sizeof(cell ***));

	// Iterate over the height of the maze
	for (int z = 0; z < MAZEHEIGHT; ++z)
	{

		// Iterate over the width of the maze
		maze[z] = (cell **)calloc(MAZEWIDTH, sizeof(cell **));
		for (int y = 0; y < MAZEWIDTH; ++y)
		{

			// Iterate over the depth of the maze
			maze[z][y] = (cell *)calloc(MAZEDEPTH, sizeof(cell ));
			for (int x = 0; x < MAZEDEPTH; ++x)
			{
	      		
    		// Set the cell's coordinates
    		maze[z][y][x].z = z;
    		maze[z][y][x].y = y;
    		maze[z][y][x].x = x;

			} // for (int x = 0; x < MAZEDEPTH; ++x)

		} // for (int y = 0; y < MAZEWIDTH; ++y)

  } // for (int z = 0; z < MAZEHEIGHT; ++z)

} // void Planner::initialize()

// ********************************************** // 
// Heap (priority queue and map) helper functions //
// ********************************************** // 

// Local method
// percolatedown: exchanges a parent cell with a child cell if the child's key is smaller than the parents key
// INPUTS: integer representing the heapindex, pointer to cell representing cell to be added or removed from the heap
// OUTPUTS: none
void percolatedown(int hole, cell *tmp)
{

  int child;

  if (heapsize != 0)
  {

    for (; 2*hole <= heapsize; hole = child)
		{
		  child = 2*hole;

		  // If we are not at the end of the heap, and the key of the next cell in the heap is smaller than the child cell's key
		  if (child != heapsize && heap[child+1]->key < heap[child]->key)
		  {

		  	// Move the child cell down the heap
		    ++child;

		  } // if (child != heapsize && heap[child+1]->key < heap[child]->key)

		  // If the child cell's key is smaller than the tmp cell's key, swap the parent and child
		  if (heap[child]->key < tmp->key)
	    {
		      
		      heap[hole] = heap[child];
		      heap[hole]->heapindex = hole;

	    } // if (heap[child]->key < tmp->key)
		  else
		  {

		    break;

		  } // if (heap[child]->key < tmp->key)

		} // for (; 2*hole <= heapsize; hole = child)

	      heap[hole] = tmp;
	      heap[hole]->heapindex = hole;

  } // if (heapsize != 0)

} // void percolatedown(int hole, cell *tmp)


// Local method
// percolateup: exchanges a parent cell with a child cell if the child's key is greater than the parents key
// INPUTS: integer representing the heapindex, pointer to cell representing cell to be added or removed from the heap
// OUTPUTS: none
void percolateup(int hole, cell *tmp)
{

  if (heapsize != 0)
  {

    for (; hole > 1 && tmp->key < heap[hole/2]->key; hole /= 2)
		{

		  heap[hole] = heap[hole/2];
		  heap[hole]->heapindex = hole;

		} // for (; hole > 1 && tmp->key < heap[hole/2]->key; hole /= 2) 

    heap[hole] = tmp;
    heap[hole]->heapindex = hole;

  } // if (heapsize != 0)

} // void percolateup(int hole, cell *tmp)


// Local method
// percolateupordown: decides whether or not the cell needs to perc up or down 
// INPUTS: integer representing the heapindex of the cell in question, a pointer to the cell in question in the heap
// OUTPUTS: none
void percolateupordown(int hole, cell *tmp)
{
  
	// If there is something in the heap
  if (heapsize != 0)
  {
    
    // If the heapindex is greater than 1 and the cell corresponding to hole/2 in the heap has a key less than that of the tmp cell
    if (hole > 1 && heap[hole/2]->key > tmp->key)
    {

			percolateup(hole, tmp);

    } // if (hole > 1 && heap[hole/2]->key > tmp->key)
    else
    {
			
			percolatedown(hole, tmp);

    } // if (hole > 1 && heap[hole/2]->key > tmp->key)

  } // if (heapsize != 0)

} // void percolateupordown(int hole, cell *tmp)


// Local method
// insertheap: insert a cell into the heap
// INPUTS: pointer to the cell that should be inserted into the heap
// OUTPUTS: none
void insertheap(cell *thiscell)
{

	// If the cell has not be percolated, percolate it up first
  if (thiscell->heapindex == 0)
  {

  	// Make sure the current heapsize does not exceed that which was allocated 
    assert(heapsize < HEAPSIZE-1);

    // Pre-increment heapsize, then use the result as the argument for percolateup
    percolateup(++heapsize, thiscell);

  } // if (thiscell->heapindex == 0)
  else
  {
    
    percolateupordown(thiscell->heapindex, heap[thiscell->heapindex]);

  } // if (thiscell->heapindex == 0)

} // void insertheap(cell *thiscell)


// Local method
// deleteheap: remove a cell from the heap
// INPUTS: pointer to cell
// OUTPUTS: none
void deleteheap(cell *thiscell)
{
  
  if (thiscell->heapindex != 0)
  {
    	
    	// Decide to perc up or down, post-decrement heapsize after removing the cell
      percolateupordown(thiscell->heapindex, heap[heapsize--]);
      thiscell->heapindex = 0;

  } // if (thiscell->heapindex != 0)

} // void deleteheap(cell *thiscell)


// Local method
// topheap: returns a pointer to the first element of the heap 
// INPUTS: none
// OUTPUTS: pointer to a cell
cell *topheap()
{
  
  // If there is nothing in the heap
  if (heapsize == 0)
  {

  	// Return a NULL pointer
    return NULL;

  } // if (heapsize == 0)

  return heap[1]; // what is heap[0]?

} // cell *topheap()


// Local method
// emptyheap: clears all cells from the heap
// INPUTS: none
// OUTPUTS: none
void emptyheap()
{

	// Iterate over the number of cells in the heap
  for (int i = 1; i <= heapsize; ++i)
  {
    
    // Set the heap indexes to zero (so when we insert a cell we perc up)
    heap[i]->heapindex = 0;

  } // for (int i = 1; i <= heapsize; ++i)

  heapsize = 0;

} // void emptyheap()


// Member function of Planner class
// updatemap: this function updates the maze including changing occupancy status, computing heuristics, updating the start and goal points
// INPUTS: 3D integer array [100][30][100] containing the map,
// pointers to eigen::matrixXfs representing the start and the goal 
// OUTPUTS: boolean capturing success or failure of the update
bool Planner::updatemap(int map[][30][100], Eigen::MatrixXf* start, Eigen::MatrixXf* goal)
{

	// Integers for iterators
  int d, l, x, y, z;
  int newx, newy, newz;

	// integers local to this function storing the start and goal coordinates in the voxel map 
  int goalx = 28, goaly = 28, goalz = 5;
  int startx = 5, starty = 5, startz = 5;
  float root;

  // Reset mazeiteration to zero to indicate that the maze is being substantially changed
  mazeiteration = 0;

  // Set the start position
  startx = floor((*start)(0,0)/RESOLUTION + 0.5);
  starty = floor((*start)(0,1)/RESOLUTION + 0.5);
  startz = floor((*start)(0,2)/RESOLUTION + 0.5);

  // Set the goal position
  goalx = floor((*goal)(0,0)/RESOLUTION + 0.5);
  goaly = floor((*goal)(0,1)/RESOLUTION + 0.5);
  goalz = floor((*goal)(0,2)/RESOLUTION + 0.5);

  // Set the iterator for the 1D voxel map array to zero
	l = 0;		

	// Iterate over the maze depth
	for (x = 0; x < MAZEDEPTH; ++x)
	{

		// Iterate over the maze height
		for (z = 0; z < MAZEHEIGHT; ++z)
  	{

			// Iterate over the maze width
			for (y = 0; y < MAZEWIDTH; ++y)
	    {
		    		
		    // Calculate the radicand of the Euclidean-distance between the goal cell and the cell at x,y,z			
      	root = (float) (z-goalz)*(z-goalz) + (y-goaly)*(y-goaly) + (x-goalx)*(x-goalx);

      	// Compute the heuristic function
	  		maze[z][y][x].h = sqrt(root);

	  		// Compute the mazeiteration (should be zero)
				maze[z][y][x].iteration = mazeiteration;

				// Record the occupancy status
				maze[z][y][x].obstacle = 0;
				if (map[x][z][y] == 3)
				{
        	
        	maze[z][y][x].obstacle = 1;

				}	// if (map[x][z][y] == 3)			

        // If the cell at x,y,z is on the boundary of the map, set it to occupied
        if (z == 0 || y == 0 || x == 0 || z == MAZEHEIGHT - 1 || y == MAZEWIDTH - 1 || x == MAZEDEPTH - 1)
        {

        	maze[z][y][x].obstacle = 1;

        } // if (z == 0 || y == 0 || x == 0 || z == MAZEHEIGHT - 1 || y == MAZEWIDTH - 1 || x == MAZEDEPTH - 1)

        // Increment the index for the 1D voxel map array
        l++;

        // if x,y,z do not exceed the boundaries
        if ( (x < MAZEDEPTH - 1) && (y < MAZEWIDTH - 1) && (z < MAZEHEIGHT - 1) )
        {   	
					
					// Iterate over the number of directions
					for (d = 0; d < DIRECTIONS; ++d)
					{

						// Set the edges of the graph to NULL pointers
						maze[z][y][x].move[d] = NULL;
					
					} // for (d = 0; d < DIRECTIONS; ++d)

    	  } // if ( (x < MAZEDEPTH - 1) && (y < MAZEWIDTH - 1) && (z < MAZEHEIGHT - 1) )
    	
    	} // for (y = 0; y < MAZEWIDTH; ++y)
		
		} // for (z = 0; z < MAZEHEIGHT; ++z)
	
	} // for (x = 0; x < MAZEDEPTH; ++x)

	// Set the mazegoal
	mazegoal = &maze[goalz][goaly][goalx];

	// Set the mazegoal's heuristic to zero (it is always zero)
	mazegoal->h = 0;

	// Set the mazestart
	mazestart = &maze[startz][starty][startx];


	// Iterate over the maze height
	for (z = 0; z < MAZEHEIGHT; ++z)
	{  

		// Iterate over the maze width
		for (y = 0; y < MAZEWIDTH; ++y)
		{
			
			// Iterate over the maze depth
			for (x = 0; x < MAZEDEPTH; ++x)
			{

    		// If the cell is not an obstacle
      	if (!maze[z][y][x].obstacle)
      	{

      		// If the x,y,z position is feasible
      		if ( (x > 0 && y > 0 && z > 0) && (x < MAZEDEPTH-1 && y < MAZEWIDTH-1 && z < MAZEHEIGHT-1) )
      		{

						// Iterate over the number of directions
						for (d = 0; d < DIRECTIONS; ++d)
					  {

					  	// Compute temporary cell position
					    newz = z + dz[d];
					    newy = y + dy[d];
					    newx = x + dx[d];

					    // If temp cell position is feasible
					    if (newz >= 0 && newz < MAZEHEIGHT && newy >= 0 && newy < MAZEWIDTH && newx >= 0 && newx < MAZEDEPTH && !maze[newz][newy][newx].obstacle)
					    {

					    	// Set the edge in the graph
					      maze[z][y][x].move[d] = &maze[newz][newy][newx];

					  	} // if (newz >= 0 && newz < MAZEHEIGHT && newy >= 0 && newy < MAZEWIDTH && newx >= 0 && newx < MAZEDEPTH && !maze[newz][newy][newx].obstacle)

	      		} // for (d = 0; d < DIRECTIONS; ++d)

    			} // if ( (x > 0 && y > 0 && z > 0) && (x < MAZEDEPTH-1 && y < MAZEWIDTH-1 && z < MAZEHEIGHT-1) )

    		} // if (!maze[z][y][x].obstacle)
    		else
    		{

					// Iterate over the number of directions
					for (d = 0; d < DIRECTIONS; ++d)
				  {

				  	// Compute temporary cell position (neighbor)
				    newz = z + dz[d];
				    newy = y + dy[d];
				    newx = x + dx[d];

				    // If temporary cell position is feasible
				    if (newz >= 0 && newz < MAZEHEIGHT && newy >= 0 && newy < MAZEWIDTH && newx >= 0 && newx < MAZEDEPTH && !maze[newz][newy][newx].obstacle)
				    {

				    	// Set the edge in the graph
				      maze[z][y][x].move[d] = &maze[newz][newy][newx];

				  	} // if (newz >= 0 && newz < MAZEHEIGHT && newy >= 0 && newy < MAZEWIDTH && newx >= 0 && newx < MAZEDEPTH && !maze[newz][newy][newx].obstacle)


    			} // for (d = 0; d < DIRECTIONS; ++d)

				} // if (!maze[z][y][x].obstacle)

			} // for (x = 0; x < MAZEDEPTH; ++x)

		} // for (y = 0; y < MAZEWIDTH; ++y)

	} // for (z = 0; z < MAZEHEIGHT; ++z)

	// Return success
	return true;

} // bool Planner::updatemap(int map[][30][100], Eigen::MatrixXf* start, Eigen::MatrixXf* goal)


void Planner::update_start_and_goal(Eigen::MatrixXf* start, Eigen::MatrixXf* goal)
{

	int startx, starty, startz;
	int goalx, goaly, goalz;

  startx = floor((*start)(0,0)/RESOLUTION + 0.5);
  starty = floor((*start)(0,1)/RESOLUTION + 0.5);
  startz = floor((*start)(0,2)/RESOLUTION + 0.5);

  goalx = floor((*goal)(0,0)/RESOLUTION + 0.5);
  goaly = floor((*goal)(0,1)/RESOLUTION + 0.5);
  goalz = floor((*goal)(0,2)/RESOLUTION + 0.5);


	mazegoal = &maze[goalz][goaly][goalx];
	mazegoal->h = 0;

	mazestart = &maze[startz][starty][startx];

}


bool time_to_stop, terminate_timing_thread, earlyTermination = false;

void initializecell(cell *thiscell)
{

  if (thiscell->iteration != mazeiteration)
  {
    thiscell->g = LARGE;
    thiscell->searchtree = NULL;
    thiscell->iteration = mazeiteration;
  } // if (thiscell->iteration != mazeiteration)

} // void initializecell(cell *thiscell)

void Planner::astarcomputeshortestpath() // = this version assumes that a cell cannot be its own successor
{
  cell *tmpcell1, *tmpcell2;
  int d;
  float root, kappa_sqrt;
  int ki;

  ++mazeiteration;
  mazestart->g = 0;
  mazestart->key = mazestart->h * BASE;
  mazestart->searchtree = NULL;
  mazestart->iteration = mazeiteration;

  emptyheap();
  insertheap(mazestart);

  while (topheap() != NULL)
	{
		if (time_to_stop)
		{
			return;
		}
  	tmpcell1 = topheap();
  	if (tmpcell1 == mazegoal)
  	{
			// cout << "breaking" << endl;
			break;

  	}
    deleteheap(tmpcell1);

		for (d = 0; d < DIRECTIONS; ++d)
  	{

			if (tmpcell1->move[d] != NULL)
			{

				tmpcell2 = tmpcell1->move[d];

				initializecell(tmpcell2);

				if (tmpcell2 != NULL)
				{

					root = (float) (tmpcell2->z - tmpcell1->z)*(tmpcell2->z - tmpcell1->z) + (tmpcell2->y - tmpcell1->y)*(tmpcell2->y - tmpcell1->y) + (tmpcell2->x - tmpcell1->x)*(tmpcell2->x - tmpcell1->x);
					kappa_sqrt = sqrt(root);
				
			  	if ( (tmpcell2->iteration != mazeiteration || tmpcell1->g + kappa_sqrt < tmpcell2->g)) 
					{

						tmpcell2->iteration = mazeiteration;
						tmpcell2->g = tmpcell1->g + 0.5*kappa_sqrt;
						tmpcell2->key = (tmpcell2->g + tmpcell2->h) * BASE + tmpcell2->g;
						tmpcell2->searchtree = tmpcell1;
	    			insertheap(tmpcell2);

					} // if (tmpcell3 != mazestart && !tmpcell3->obstacle && tmpcell3->z > 0 && tmpcell1->g + kappa_sqrt < tmpcell3->g)

				} // if (tmpcell3->move[d] != NULL)

			} // if (tmpcell1->move[d] != NULL)

		} // for (d = 0; d < DIRECTIONS; ++d)

  } // while (topheap() != NULL)

} // void Planner::astarcomputeshortestpath()



void Planner::testastar() // = this version is specific to mazes
{

	int d;
	cell *tmpcell1;

	astarcomputeshortestpath();

	if (topheap() != NULL)
	{
			tmpcell1 = mazegoal;

			for (d = 0; tmpcell1 != mazestart; ++d, tmpcell1 = tmpcell1->searchtree)
			{

				if (d >= 900)
				{
					success = false;
					cout << "Did not trace a path" << endl;
					return;
				}

			} // for (d = 0; tmpcell1 != mazestart; ++d, tmpcell1 = tmpcell1->searchtree)

			success = true;

	} // if (mazegoal->g != LARGE)

} // void Planner::testastar() // = this version is specific to mazes

// Local method
// astar_timing_thread: This thread runs a timer, if the lpastar search takes too long (as measured by the timer in this thread)
// then the lpastar search is terminated, and this thread resets once the next call to the lpastar search is executed
// INPUTS: void pointer to some object (no needed)
// OUTPUTS: void pointer
void* astar_timing_thread(void *args)
{

	// Timing variables
	auto current_time = std::chrono::high_resolution_clock::now();
	auto end_time = std::chrono::high_resolution_clock::now();
	std::chrono::duration<double> timeElapsed = end_time - current_time;

	// cout <<" Started timing thread!" << endl;

	// While loop that ends when LPA* finds a path or the timer expires 
	while(!terminate_timing_thread)
	{

		// Update the time
		end_time = std::chrono::high_resolution_clock::now();
		
		// Compute the elapsed time
		timeElapsed = end_time - current_time;
		
		// If the timer has expired (10 seconds have passed)
		if (std::chrono::duration_cast<chrono::seconds>(timeElapsed).count() > 5)
		{
			cout << "Time to stop LPA*, taking too long!" << endl;
			
			// Signal to end the while loop
			terminate_timing_thread = true;
			
			// Signal to LPA* search process to end
			time_to_stop = true;
			earlyTermination = true;

		} // if (std::chrono::duration_cast<chrono::seconds>(timeElapsed).count() > 10)
	
	} // while(!terminate_timing_thread)

	// cout << "Ending timing thread!" << endl;

	return NULL;

} // void* lpa_timing_thread(void *args)




bool Planner::astar()
{

	int writeStatus = 0;

	string message;

	auto current_time = std::chrono::high_resolution_clock::now();
	auto end_time = std::chrono::high_resolution_clock::now();
	std::chrono::duration<double> timeElapsed = end_time - current_time;
	
	// Pthread ID for the timing thread
	pthread_t astar_timing_tid;

	// Reset the timing thread variable
  time_to_stop = false; 	terminate_timing_thread = false, earlyTermination = false;

	if (mazegoal->obstacle)
	{
		cout << "A*: Goal is occupied" << endl;
		return false;
	}

  // Start the timing thread
	int	result_astar_timing = pthread_create( &astar_timing_tid, NULL, &astar_timing_thread, this);	

	// Start LPA* search
	testastar();	

	// If the LPA* search ends before the timing thread expires, terminate the timing thread
	terminate_timing_thread = true;

	if (earlyTermination)
	{
		success = false;
	}

	// Join the timing thread (ending it)
	pthread_join(astar_timing_tid,NULL);

	end_time = std::chrono::high_resolution_clock::now();
	timeElapsed = end_time - current_time;
	// cout << ">> Elapsed time [seconds]: " << timeElapsed.count() << endl;

	return success;

} // void Planner::Astar()

